### ISSUE TITLE
HTTP POST Notification

### ISSUE THREAD

**Issue by weslambert** [3CORESec/Trapdoor#2]
I really appreciate all the hard work you guys have put into this!  It's really cool!  It's great that we are able to alert to Slack, but it would also be really cool if we are able to perform a generic HTTP post to an endpoint/listener.  I would be glad to help in any way I can with development/testing, etc.

**Comment by 0xtf** [comment]
https://github.com/3CORESec/Trapdoor/commit/c0342653034aada7794199bf92e52061aa752ff0

**Comment by 0xtf** [comment]
Thank you for the FR @weslambert! Ping us if anything comes up. Closing this one for now. @pdr9rc you rock 🎸 🤘🏼

**Comment by weslambert** [comment]
Thanks for working on this so quickly! Yes, you are awesome @pdr9rc!

**Comment by pdr9rc** [comment]
No problem! If anything comes up, let me know! 🤘
